version: 0.2

phases:
  install: 
    commands:
      - go get -u github.com/golang/lint/golint
      - curl https://glide.sh/get | sh

  pre_build:
    commands:
      - glide up

  build:
    commands:
      - go build -o saltgopher . 

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - saltgopher
  discard-paths: yes