version: 0.2

phases:
  install: 
    commands:
      - go get -u github.com/golang/lint/golint
      - sudo add-apt-repository ppa:masterminds/glide 
      - sudo apt-get update
      - sudo apt-get install glide

  pre_build:
    commands:
      - glide up

  build:
    commands:
      - go build -o saltgopher . 

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - saltgopher
  discard-paths: yes