version: 0.2

environment_variables:
  plaintext:
    PACKAGE: "github.com/simianlabs/saltgopher"

phases:
  install: 
    commands:
      - go get -u github.com/golang/lint/golint
      - sudo add-apt-repository ppa:masterminds/glide 
      - sudo apt-get update
      - sudo apt-get install -y glide

  pre_build:
    commands:
      - echo Create dir in GOPATH for sources
      - mkdir -p ${GOPATH}/src/${PACKAGE}
      - echo Copy source files into GOPATH
      - echo cp -a ${CODEBUILD_SRC_DIR}/.  ${GOPATH}/src/${PACKAGE}
      - cp -a ${CODEBUILD_SRC_DIR}/.  ${GOPATH}/src/${PACKAGE}
      - cd ${GOPATH}/src/${PACKAGE} && glide up

  build:
    commands:
      - ls -laR ${GOPATH}/src/
      # - cd ${GOPATH}/src/${PACKAGE} && go build -o ${CODEBUILD_SRC_DIR}/saltgopher . 

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - saltgopher
  discard-paths: yes