version: 0.2

phases:
  install: 
    commands:
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/golang/dep/cmd/dep
      - mkdir -p $GOPATH/src/saltgopher

  pre-build:
    commands:
      - ls -la
      - dep ensure

  build:
    commands:
      - go build -o saltgopher . 

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - saltgopher
  discard-paths: yes